blueprint:
  # Based on work by [@gmlupatelli](https://github.com/gmlupatelli/)
  name: Unavailable entity detection & notification
  description:  Regularly test all entities' status to check for unavailability, and if so execute one or more actions.
  domain: automation
  source_url: https://github.com/chjohans/blueprints_repo/blob/master/unavailable_entities_notification/unavailable_entities_notification.yaml

  input:
    time:
      name: Time to run automation
      description: Automation is being executed at the configured time
      default: '09:00:00'
      selector:
        time: {}

    monday_enabled:
      name: Monday
      description: Run automation every Monday
      default: true
      selector:
        boolean:
    tuesday_enabled:
      name: Tuesday
      description: Run automation every Tuesday
      default: true
      selector:
        boolean:
    wednesday_enabled:
      name: Wednesday
      description: Run automation every Wednesday
      default: true
      selector:
        boolean:
    thursday_enabled:
      name: Thursday
      description: Run automation every Thursday
      default: true
      selector:
        boolean:
    friday_enabled:
      name: Friday
      description: Run automation every Friday
      default: true
      selector:
        boolean:
    saturday_enabled:
      name: Saturday
      description: Run automation every Saturday
      default: true
      selector:
        boolean:
    sunday_enabled:
      name: Sunday
      description: Run automation every Sunday
      default: true
      selector:
        boolean:

    exclude:
      name: Excluded Entities
      description: Entities (e.g. smartphones and tables) to exclude from detection. Only entities are supported, areas and devices must be expanded!
      default: {}
      selector:
        target:
        
    actions:
      name: Actions
      description: Notifications or similar to be run. {{entities}} is replaced with the names of unavailable entities.
      selector:
        action:

variables:
  monday_enabled: !input 'monday_enabled'
  tuesday_enabled: !input 'tuesday_enabled'
  wednesday_enabled: !input 'wednesday_enabled'
  thursday_enabled: !input 'thursday_enabled'
  friday_enabled: !input 'friday_enabled'
  saturday_enabled: !input 'saturday_enabled'
  sunday_enabled: !input 'sunday_enabled'

  current_day: '{{ now().weekday() | int }}'

  exclude: !input 'exclude'

  entities: >-
    {% set result = namespace(entities=[]) %}
    {% for state in states %}
      {% if exclude.entity_id is defined %}
        {% if state.state == 'unavailable' and not state.entity_id in exclude.entity_id %}
          {% set result.entities = result.entities + [state.name] %}
        {% endif %}
      {% else %}
        {% if state.state == 'unavailable' %}
          {% set result.entities = result.entities + [state.name] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{"⤵ \n- "}}{{result.entities|join('\n- ')}}

trigger:
  - platform: time
    at: !input 'time'
condition:
  - '{{ entities != '''' and ((current_day == 0 and monday_enabled) or (current_day == 1 and tuesday_enabled) or (current_day == 2 and wednesday_enabled) or (current_day == 3 and thursday_enabled) or (current_day == 4 and friday_enabled) or (current_day == 5 and saturday_enabled) or (current_day == 6 and sunday_enabled)) }}'
action:
  - choose: []
    default: !input 'actions'
mode: single
max_exceeded: silent