blueprint:
  # Based on work by [@raffy-ops](https://github.com/raffy-ops)
  name: HVAC Pause/Restore
  description: Pauses HVAC when windows/doors are opened, and if HVAC is started while windows/doors are open. Resumes the previous state once the windows/doors has been closed.
  domain: automation
  source_url: https://github.com/chjohans/blueprints_repo/blob/master/hvac_pause_resume/hvac_pause_resume.yaml
  
  input:
    climate_device:
      description: Climate entity used for climate control.
      name: Climate Device
      selector:
        entity:
          domain: climate
          multiple: false
    doors_windows:
      description: Group of entities that will activate automation. (Assumes 'on'
        means 'open')
      name: Door and window sensors.
      selector:
        entity:
          domain:
          - group
          - binary_sensor
          multiple: false
    pause_delay:
      description: Time to wait before pausing the HVAC system.
      name: Pause Delay
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration: {}
    resume_delay:
      description: Time to wait before resuming the HVAC system.
      name: Resume Delay
      default:
        hours: 0
        minutes: 0
        seconds: 30
      selector:
        duration: {}
    pause_action:
      description: Optional additional action to perform when HVAC entity is paused.
      name: Pause Action (Optional)
      default: []
      selector:
        action: {}
    resume_action:
      description: Optional additional action to perform when HVAC entity resumes.
      name: Resume Action (Optional)
      default: []
      selector:
        action: {}
variables:
  pause_action: !input pause_action
  resume_action: !input resume_action
mode: restart

trigger:
- platform: state
  entity_id: !input doors_windows
  from: 'off'
  to: 'on'
  for: !input pause_delay
  id: group_open
- platform: state
  entity_id: !input climate_device
  from: 'off'

condition:
- condition: and
  conditions:
  - condition: not
    conditions:
    - condition: state
      entity_id: !input climate_device
      state: 'off'
  - condition: state
    entity_id: !input doors_windows
    state: 'on'
    
action:
- service: scene.create
  data:
    scene_id: climate_snapshot
    snapshot_entities: !input climate_device
- service: climate.set_hvac_mode
  target:
    entity_id: !input climate_device
  data:
    hvac_mode: 'off'
- choose:
  - conditions: '{{ pause_action is defined }}'
    sequence: !input pause_action
- wait_for_trigger:
  - platform: state
    entity_id: !input doors_windows
    from: 'on'
    to: 'off'
    for: !input resume_delay
  continue_on_timeout: false
- scene: scene.climate_snapshot
- choose:
  - conditions: '{{ resume_action is defined }}'
    sequence: !input resume_action
